"""empty message

Revision ID: 6c1c36f3025d
Revises: 0cc20bcdefe2
Create Date: 2025-01-14 12:47:07.465580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1c36f3025d'
down_revision = '0cc20bcdefe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_activities_date_id_dates'), 'dates', ['date_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activities_date_id_dates'), type_='foreignkey')
        batch_op.drop_column('date_id')

    # ### end Alembic commands ###
